- name: Install mysql
  yum:
    name: 
      - mariadb
      - mariadb-server
    state: present

- name: Enable msql
  service:
    name: mariadb
    state: started
    enabled: yes
    
- name: Create database
  shell: mysql -e "create database if not exists {{ db_name }};"


- name: Create user
  shell: mysql -e "CREATE USER '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';"

- name: grant privileges
  shell: mysql -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';"

- name: flush privileges
  shell: mysql -e "flush privileges;"